"""Video amplifier: auto-contrast, brightness, gamma and polarity.

Between the detector and the digitiser sits the video chain, and on a real tool
an operator (or an auto-contrast routine) sets its gain and offset so the
histogram fills the 8-bit range.  Modelling it matters for two reasons.

**Without it the images clip.**  The edge-brightening term adds signal on top of
the material map, so the raw sum routinely exceeds 1.0.  An early version of
this generator produced search images with a mean of 183/255 and 14 % of pixels
pinned at white; the saturated pixels carry no information and the effective
contrast collapses.  Normalising the working range first, then applying an
explicit contrast and brightness, keeps saturation near 1 % and makes those two
parameters mean what they say.

**Polarity is a real failure mode.**  Whether features come out bright on dark
or dark on bright depends on detector selection (SE vs BSE), landing energy and
the material stack.  A model trained on one polarity fails completely on the
other.  Randomising it costs one line and removes an entire class of brittleness
-- the hidden test set is generated by someone else's parameter choices.

Gamma is the digitiser's transfer curve; it is deliberately applied *before*
shot noise, because the noise is generated in the detector, not after it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict

import numpy as np

from driftsense.config import OpticsConfig


@dataclass(frozen=True)
class VideoParams:
    """Sampled video-chain settings for one frame.

    Attributes:
        contrast: Gain applied after normalisation.
        brightness: Offset applied after gain (black level).
        gamma: Transfer-curve exponent.
        invert: Whether the frame comes out with inverted polarity.
        norm_lo: Lower percentile used for auto-range.
        norm_hi: Upper percentile used for auto-range.
    """

    contrast: float
    brightness: float
    gamma: float
    invert: bool = False
    norm_lo: float = 1.0
    norm_hi: float = 99.5

    @classmethod
    def sample(cls, rng: np.random.Generator, cfg: OpticsConfig) -> "VideoParams":
        """Draw video settings for one frame."""
        return cls(
            contrast=cfg.contrast.draw(rng),
            brightness=cfg.brightness.draw(rng),
            gamma=cfg.gamma.draw(rng),
            invert=bool(rng.random() < cfg.invert_probability),
        )

    def normalise(self, img: np.ndarray) -> np.ndarray:
        """Stretch the working range using robust percentiles.

        The percentiles are computed on every fourth pixel in each axis -- a
        1/16 subsample.  At 1000x1000 that turns a 12 ms sort into under 1 ms,
        and the percentile of a 62 500-pixel subsample differs from the true one
        by far less than the quantisation step.
        """
        sub = img[::4, ::4]
        lo = float(np.percentile(sub, self.norm_lo))
        hi = float(np.percentile(sub, self.norm_hi))
        out = (img - lo) / (hi - lo + 1e-6)
        # A little headroom either side: real detectors do clip, occasionally.
        return np.clip(out, -0.15, 1.4, out=out if out.dtype == np.float32 else None)

    def apply(self, img: np.ndarray) -> np.ndarray:
        """Run the full video chain.

        Args:
            img: Detector-stage image (``float32``).

        Returns:
            ``float32`` image in signal units, nominally ``[0, 1]``, ready for
            shot noise.
        """
        out = self.normalise(np.ascontiguousarray(img, dtype=np.float32))
        out = out * np.float32(self.contrast) + np.float32(self.brightness)
        np.clip(out, 0.0, None, out=out)
        if self.gamma != 1.0:
            out = np.power(out, np.float32(self.gamma), dtype=np.float32)
        if self.invert:
            peak = float(out.max())
            out = np.float32(peak) - out
        return out

    def to_dict(self) -> Dict[str, Any]:
        """Manifest view."""
        return {
            "contrast": round(self.contrast, 4),
            "brightness": round(self.brightness, 4),
            "gamma": round(self.gamma, 4),
            "invert": bool(self.invert),
        }


# --------------------------------------------------------------------------- #
# Self-test
# --------------------------------------------------------------------------- #
def _self_test() -> None:
    """Run ``python -m driftsense.optics.video``."""
    import json

    from driftsense.config import GeneratorConfig

    cfg = GeneratorConfig()
    p = VideoParams.sample(np.random.default_rng(6), cfg.search_optics)
    assert p == VideoParams.sample(np.random.default_rng(6), cfg.search_optics)

    rng = np.random.default_rng(0)
    base = (rng.random((256, 256)).astype(np.float32) * 0.5 + 0.2)

    # 1. normalisation is scale- and offset-invariant, which is what makes the
    #    contrast/brightness parameters portable across layouts
    a = p.apply(base)
    b = p.apply(base * 3.0 + 0.7)
    assert float(np.abs(a - b).max()) < 0.02, float(np.abs(a - b).max())

    # 2. the saturation bug this module exists to prevent
    edgey = base + 0.8 * np.abs(np.diff(base, axis=1, prepend=0.0)).astype(np.float32)
    edgey += 0.6                                    # simulate an edge-boosted frame
    out = VideoParams(0.65, 0.18, 1.0).apply(edgey)
    sat = float((out >= 1.0).mean())
    assert sat < 0.05, f"{100*sat:.1f} % saturated"
    assert 0.2 < float(out.mean()) < 0.8, float(out.mean())

    # 3. contrast and brightness do what they are named
    lo_c = VideoParams(0.4, 0.2, 1.0).apply(base)
    hi_c = VideoParams(0.8, 0.2, 1.0).apply(base)
    assert float(hi_c.std()) > 1.7 * float(lo_c.std())
    dim = VideoParams(0.6, 0.05, 1.0).apply(base)
    bright = VideoParams(0.6, 0.35, 1.0).apply(base)
    assert float(bright.mean()) - float(dim.mean()) > 0.25

    # 4. gamma is monotone and order-preserving
    g = VideoParams(0.7, 0.15, 1.6).apply(base)
    order_in = np.argsort(base.ravel())
    assert np.all(np.diff(g.ravel()[order_in]) >= -1e-6)

    # 5. inversion flips contrast without changing its magnitude
    normal = VideoParams(0.7, 0.15, 1.0, invert=False).apply(base)
    flipped = VideoParams(0.7, 0.15, 1.0, invert=True).apply(base)
    r = float(np.corrcoef(normal.ravel(), flipped.ravel())[0, 1])
    assert r < -0.99, r
    assert abs(float(normal.std()) - float(flipped.std())) < 1e-4

    # 6. dtype discipline and finiteness
    assert normal.dtype == np.float32 and np.isfinite(normal).all()

    json.dumps(p.to_dict())

    print("optics/video.py self-test OK")
    print(f"  sampled                : contrast {p.contrast:.2f}, "
          f"brightness {p.brightness:.2f}, gamma {p.gamma:.2f}, invert {p.invert}")
    print(f"  scale/offset invariance: max delta {float(np.abs(a-b).max()):.4f}")
    print(f"  saturation on edgy input: {100*sat:.2f} %")
    print(f"  inverted correlation   : r = {r:.4f}")


if __name__ == "__main__":
    _self_test()
